### ISSUE TITLE
ERROR: Failed to open HMI serial port

### ISSUE THREAD

**Issue by ericfont** [moddevices/mod-ui#121]
Trying on Debian 11 (bullseye) x86-64 but I get the following error:

```(modui-env) e@efjz:~/mod-ui$ python3 ./server.py
Can't create a device key: module 'time' has no attribute 'clock'
WARN: Missing file /home/e/mod-ui/data/mod_api_key.pub with the public API KEY
ERROR: Failed to open HMI serial port, error was:
__init__() got an unexpected keyword argument 'writeTimeout'
Using FakeHMI => <mod.development.FakeHMI object at 0x7f982541fa60>
cc start socket missing
Traceback (most recent call last):
  File "/home/e/mod-ui/./server.py", line 56, in <module>
    webserver.run()
  File "/home/e/mod-ui/mod/webserver.py", line 2361, in run
    prepare()
  File "/home/e/mod-ui/mod/webserver.py", line 2332, in prepare
    application.listen(DEVICE_WEBSERVER_PORT, address="0.0.0.0")
  File "/home/e/mod-ui/modui-env/lib/python3.9/site-packages/tornado/web.py", line 1825, in listen
    server.listen(port, address)
  File "/home/e/mod-ui/modui-env/lib/python3.9/site-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/e/mod-ui/modui-env/lib/python3.9/site-packages/tornado/netutil.py", line 196, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
jack client deactivated NOT
```

**Comment by ericfont** [comment]
oh silly me, the other terminal I had for mod-host reported that HMI setup failed...so that is why my probllem is:

```
mod-host -n -p 5555 -f 5556
shm_open failed
sys_host HMI setup failed
mod-host ready!
```

**Comment by ericfont** [comment]
though mod-host works if I downgrade to hotfix-1.10 branch

**Comment by ericfont** [comment]
still can't figure it up, but I've gave up

**Comment by ericfont** [comment]
I eventually did get it working on my Debian 11 desktop, after much installing and uninstalling of things.
