### ISSUE TITLE
module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by apiel** [moddevices/mod-ui#136]
I was trying to follow step by step the installation on my ubuntu but I am getting:

```
Can't create a device key: No module named 'Cryptodome'
WARN: Missing file /home/alex/Music/mod/mod-ui/data/mod_api_key.pub with the public API KEY
Traceback (most recent call last):
  File "/home/alex/Music/mod/mod-ui/./server.py", line 54, in <module>
    from mod import webserver
  File "/home/alex/Music/mod/mod-ui/mod/webserver.py", line 31, in <module>
    from tornado import gen, iostream, web, websocket
  File "/home/alex/Music/mod/mod-ui/modui-env/lib/python3.11/site-packages/tornado/web.py", line 85, in <module>
    from tornado import httputil
  File "/home/alex/Music/mod/mod-ui/modui-env/lib/python3.11/site-packages/tornado/httputil.py", line 101, in <module>
    class HTTPHeaders(collections.MutableMapping):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

I would love to be able to set it up on my laptop because I want to develop my own LV2 plugin...

Actually would be great to have a dev environment using docker.

**Comment by apiel** [comment]
Doens't python have some version manager like nvmrc for nodejs?

**Comment by falkTX** [comment]
there is pip, but that is for installing packages. mod-ui needs older versions of tornado which are not compatible with python3.10+ without hacks

**Comment by apiel** [comment]
Alright, then i will have a look to mod-panel, thx ;-)
