### ISSUE TITLE
./setup.py server is not starting after performing installation process

### ISSUE THREAD

**Issue by Bigjuergo** [moddevices/mod-ui#56]
when i type ./server.py in the terminal after installing the mod-ui i get the following error:
```
(modui-env) root@bigjuergo-X550LA:/home/bigjuergo/Downloads/mod-ui# ./server.py
Traceback (most recent call last):
  File "./server.py", line 47, in <module>
    create_dummy_credentials()
  File "./server.py", line 13, in create_dummy_credentials
    with open(os.environ['MOD_DEVICE_TAG'], 'w') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bigjuergo/Downloads/mod-ui/data/tag'
```
can you help me please?
(i use ubuntu studio 64bit as operating system)

thank you.

**Comment by alercunha** [comment]
Fixed by https://github.com/moddevices/mod-ui/commit/46e5a3d22e781990d33c1f07a51de5db3847ab65

**Comment by Bigjuergo** [comment]
it works now, thank you very much!
